TYPE=VIEW
query=select `dt`.`dt_id` AS `dt_id`,`dt`.`_date` AS `_date`,`dt`.`_datetime` AS `_datetime`,`dt`.`_time` AS `_time`,`dt`.`_timestamp` AS `_timestamp`,`dt`.`_year` AS `_year`,`dt`.`_nullDate` AS `_nullDate`,`dt`.`_nullDatetime` AS `_nullDatetime`,`dt`.`_nullTime` AS `_nullTime`,`dt`.`_nullTimestamp` AS `_nullTimestamp`,`dt`.`_nullYear` AS `_nullYear`,`gt`.`gt_id` AS `gt_id`,`gt`.`_point` AS `_point`,`gt`.`_linestring` AS `_linestring`,`gt`.`_polygon` AS `_polygon`,`gt`.`_multipoint` AS `_multipoint`,`gt`.`_multilinestring` AS `_multilinestring`,`gt`.`_multipolygon` AS `_multipolygon`,`gt`.`_geometrycollection` AS `_geometrycollection`,`gt`.`_nullPoint` AS `_nullPoint`,`gt`.`_nullLinestring` AS `_nullLinestring`,`gt`.`_nullPolygon` AS `_nullPolygon`,`gt`.`_nullMultipoint` AS `_nullMultipoint`,`gt`.`_nullMultilinestring` AS `_nullMultilinestring`,`gt`.`_nullMultipolygon` AS `_nullMultipolygon`,`gt`.`_nullGeometrycollection` AS `_nullGeometrycollection`,`nt`.`nt_id` AS `nt_id`,`nt`.`_uint` AS `_uint`,`nt`.`_int` AS `_int`,`nt`.`_tinyint` AS `_tinyint`,`nt`.`_smallint` AS `_smallint`,`nt`.`_mediumint` AS `_mediumint`,`nt`.`_bigint` AS `_bigint`,`nt`.`_decimal` AS `_decimal`,`nt`.`_double` AS `_double`,`nt`.`_float` AS `_float`,`nt`.`_real` AS `_real`,`nt`.`_bit1` AS `_bit1`,`nt`.`_bit24` AS `_bit24`,`nt`.`_bitWithDefault` AS `_bitWithDefault`,`nt`.`_bitWithDefault2` AS `_bitWithDefault2`,`nt`.`_nullUint` AS `_nullUint`,`nt`.`_nullInt` AS `_nullInt`,`nt`.`_nullTinyint` AS `_nullTinyint`,`nt`.`_nullSmallint` AS `_nullSmallint`,`nt`.`_nullMediumint` AS `_nullMediumint`,`nt`.`_nullBigint` AS `_nullBigint`,`nt`.`_nullDecimal` AS `_nullDecimal`,`nt`.`_nullDouble` AS `_nullDouble`,`nt`.`_nullFloat` AS `_nullFloat`,`nt`.`_nullReal` AS `_nullReal`,`nt`.`_nullBit1` AS `_nullBit1`,`nt`.`_nullBit24` AS `_nullBit24`,`ot`.`ot_id` AS `ot_id`,`ot`.`_blob` AS `_blob`,`ot`.`_tinyblob` AS `_tinyblob`,`ot`.`_mediumblob` AS `_mediumblob`,`ot`.`_longblob` AS `_longblob`,`ot`.`_binary` AS `_binary`,`ot`.`_varbinary` AS `_varbinary`,`ot`.`_enum` AS `_enum`,`ot`.`_set` AS `_set`,`ot`.`_alwaysNull` AS `_alwaysNull`,`ot`.`populatedViaTrigger` AS `populatedViaTrigger`,`ot`.`populatedViaTrigger2` AS `populatedViaTrigger2`,`ot`.`_nullBlob` AS `_nullBlob`,`ot`.`_nullTinyblob` AS `_nullTinyblob`,`ot`.`_nullMediumblob` AS `_nullMediumblob`,`ot`.`_nullLongblob` AS `_nullLongblob`,`ot`.`_nullBinary` AS `_nullBinary`,`ot`.`_nullVarbinary` AS `_nullVarbinary`,`ot`.`_nullEnum` AS `_nullEnum`,`ot`.`_nullSet` AS `_nullSet` from (((`mysqldump_test`.`date_types` `dt` join `mysqldump_test`.`geometry_types` `gt` on((`dt`.`dt_id` = `gt`.`gt_id`))) join `mysqldump_test`.`number_types` `nt` on((`dt`.`dt_id` = `nt`.`nt_id`))) join `mysqldump_test`.`other_types` `ot` on((`dt`.`dt_id` = `ot`.`ot_id`)))
md5=00bc22b89aefbb9d515f62f2b3ca9959
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2024-06-03 18:12:35
create-version=1
source=SELECT *\n  FROM date_types AS dt\n INNER JOIN geometry_types AS gt\n    ON dt.dt_id = gt.gt_id\n INNER JOIN number_types AS nt\n    ON dt.dt_id = nt.nt_id\n INNER JOIN other_types AS ot\n    ON dt.dt_id = ot.ot_id
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `dt`.`dt_id` AS `dt_id`,`dt`.`_date` AS `_date`,`dt`.`_datetime` AS `_datetime`,`dt`.`_time` AS `_time`,`dt`.`_timestamp` AS `_timestamp`,`dt`.`_year` AS `_year`,`dt`.`_nullDate` AS `_nullDate`,`dt`.`_nullDatetime` AS `_nullDatetime`,`dt`.`_nullTime` AS `_nullTime`,`dt`.`_nullTimestamp` AS `_nullTimestamp`,`dt`.`_nullYear` AS `_nullYear`,`gt`.`gt_id` AS `gt_id`,`gt`.`_point` AS `_point`,`gt`.`_linestring` AS `_linestring`,`gt`.`_polygon` AS `_polygon`,`gt`.`_multipoint` AS `_multipoint`,`gt`.`_multilinestring` AS `_multilinestring`,`gt`.`_multipolygon` AS `_multipolygon`,`gt`.`_geometrycollection` AS `_geometrycollection`,`gt`.`_nullPoint` AS `_nullPoint`,`gt`.`_nullLinestring` AS `_nullLinestring`,`gt`.`_nullPolygon` AS `_nullPolygon`,`gt`.`_nullMultipoint` AS `_nullMultipoint`,`gt`.`_nullMultilinestring` AS `_nullMultilinestring`,`gt`.`_nullMultipolygon` AS `_nullMultipolygon`,`gt`.`_nullGeometrycollection` AS `_nullGeometrycollection`,`nt`.`nt_id` AS `nt_id`,`nt`.`_uint` AS `_uint`,`nt`.`_int` AS `_int`,`nt`.`_tinyint` AS `_tinyint`,`nt`.`_smallint` AS `_smallint`,`nt`.`_mediumint` AS `_mediumint`,`nt`.`_bigint` AS `_bigint`,`nt`.`_decimal` AS `_decimal`,`nt`.`_double` AS `_double`,`nt`.`_float` AS `_float`,`nt`.`_real` AS `_real`,`nt`.`_bit1` AS `_bit1`,`nt`.`_bit24` AS `_bit24`,`nt`.`_bitWithDefault` AS `_bitWithDefault`,`nt`.`_bitWithDefault2` AS `_bitWithDefault2`,`nt`.`_nullUint` AS `_nullUint`,`nt`.`_nullInt` AS `_nullInt`,`nt`.`_nullTinyint` AS `_nullTinyint`,`nt`.`_nullSmallint` AS `_nullSmallint`,`nt`.`_nullMediumint` AS `_nullMediumint`,`nt`.`_nullBigint` AS `_nullBigint`,`nt`.`_nullDecimal` AS `_nullDecimal`,`nt`.`_nullDouble` AS `_nullDouble`,`nt`.`_nullFloat` AS `_nullFloat`,`nt`.`_nullReal` AS `_nullReal`,`nt`.`_nullBit1` AS `_nullBit1`,`nt`.`_nullBit24` AS `_nullBit24`,`ot`.`ot_id` AS `ot_id`,`ot`.`_blob` AS `_blob`,`ot`.`_tinyblob` AS `_tinyblob`,`ot`.`_mediumblob` AS `_mediumblob`,`ot`.`_longblob` AS `_longblob`,`ot`.`_binary` AS `_binary`,`ot`.`_varbinary` AS `_varbinary`,`ot`.`_enum` AS `_enum`,`ot`.`_set` AS `_set`,`ot`.`_alwaysNull` AS `_alwaysNull`,`ot`.`populatedViaTrigger` AS `populatedViaTrigger`,`ot`.`populatedViaTrigger2` AS `populatedViaTrigger2`,`ot`.`_nullBlob` AS `_nullBlob`,`ot`.`_nullTinyblob` AS `_nullTinyblob`,`ot`.`_nullMediumblob` AS `_nullMediumblob`,`ot`.`_nullLongblob` AS `_nullLongblob`,`ot`.`_nullBinary` AS `_nullBinary`,`ot`.`_nullVarbinary` AS `_nullVarbinary`,`ot`.`_nullEnum` AS `_nullEnum`,`ot`.`_nullSet` AS `_nullSet` from (((`mysqldump_test`.`date_types` `dt` join `mysqldump_test`.`geometry_types` `gt` on((`dt`.`dt_id` = `gt`.`gt_id`))) join `mysqldump_test`.`number_types` `nt` on((`dt`.`dt_id` = `nt`.`nt_id`))) join `mysqldump_test`.`other_types` `ot` on((`dt`.`dt_id` = `ot`.`ot_id`)))
