version: "3.8"
volumes:
  # the name of a volume to be used to store the database folder
  # the same is used at "- ./app_x_mysql_data:/var/lib/mysql"
  app_x_mysql_data:
    driver: local
services:
  app_x_mysql_service:
    image: mysql:latest
    container_name: app_x_mysql_database
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      # the location of the database folder
      - ./app_x_mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p",
          "password",
        ]
      timeout: 20s
      retries: 10
  app_x_database_flyway_migrations:
    container_name: app_x_db_flyway_migrations
    environment:
      - FLYWAY_USER=${DB_NAME}
      - FLYWAY_PASSWORD=${DB_PASSWORD}
      - FLYWAY_URL=jdbc:mysql://app_x_mysql_service:${DB_PORT}/${DB_NAME}
      - FLYWAY_SCHEMAS=flyway
      - FLYWAY_GROUP=true
    volumes:
      - $PWD/migrations:/flyway/sql
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    env_file:
      - .env
    depends_on:
      app_x_mysql_service:
        condition: service_healthy
