version: "3.8"
volumes:
  # the name of a volume to be used to store the database folder
  # the same is used at "- ./localhost_mysql_data:/var/lib/mysql"
  localhost_mysql_data:
    driver: local
services:
  localhost_mysql_data_service:
    image: mysql:latest
    container_name: localhost_mysql_data
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      # the location of the database folder
      - ./localhost_mysql_data:/var/lib/mysql
    # command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p",
          "password",
        ]
      timeout: 20s
      retries: 10
